doctrine:
    dbal:
        driver: 'pdo_pgsql'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
        charset: 'utf8'
        sslmode: 'prefer'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Core:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Core/Entity'
              prefix: 'App\Domain\Core\Entity'
              alias: Core
            Account:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Account/Entity'
              prefix: 'App\Domain\Account\Entity'
              alias: Account
            Application:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Application/Entity'
              prefix: 'App\Domain\Application\Entity'
              alias: Application
            EventPlanning:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/EventPlanning/Entity'
              prefix: 'App\Domain\EventPlanning\Entity'
              alias: EventPlanning
            Incidents:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Incidents/Entity'
              prefix: 'App\Domain\Incidents\Entity'
              alias: Incidents
            Integrations:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Integrations/Entity'
              prefix: 'App\Domain\Integrations\Entity'
              alias: Integrations
            Kanban:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Kanban/Entity'
              prefix: 'App\Domain\Kanban\Entity'
              alias: Kanban
            Map:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/Map/Entity'
              prefix: 'App\Domain\Map\Entity'
              alias: Map
            StoryMarketplace:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/StoryMarketplace/Entity'
              prefix: 'App\Domain\StoryMarketplace\Entity'
              alias: StoryMarketplace
            StoryObject:
              type: attribute
              is_bundle: false
              dir: '%kernel.project_dir%/src/Domain/StoryObject/Entity'
              prefix: 'App\Domain\StoryObject\Entity'
              alias: StoryObject
            loggable:
                type: attribute
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
        controller_resolver:
            auto_mapping: false
        dql:
            string_functions:
                JSON_GET_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
                JSONB_EXISTS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonbExists
                JSONB_EXISTS_ANY: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonbExistsAny
                JSONB_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonbContains

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
