security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username


  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    ROLE_USER: [
      'ROLE_PLAYER',
      'ROLE_ORGANIZER',
      'ROLE_STAFF'
    ]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      lazy: true
      custom_authenticators:
        - App\Security\DiscordAuthenticator
        - App\Security\FacebookAuthenticator
        - App\Security\GoogleAuthenticator
      entry_point: App\Security\GoogleAuthenticator
      logout:
        path: /logout
    player:
      lazy: true
      provider: app_user_provider
      pattern: ^/player
    backoffice:
      lazy: false
      provider: app_user_provider
      pattern: ^/backoffice
      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/backoffice, roles: ['ROLE_USER'] }
    - { path: ^/player, roles: [ 'ROLE_USER' ] }
    - { path: ^/account, roles: [ 'ROLE_USER' ] }
    - { path: ^/api, roles: [ 'ROLE_API_USER', 'ROLE_USER' ] }
    # LARP Backoffice Access Control
    - { path: ^/backoffice/larp/[^/]+/, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon