twig:
    file_name_pattern: '*.twig'
    globals:
        google_api_key: '%google_api_key%'
        google_maps_api_key: '%google_maps_api_key%'
        google_app_id: '%google_app_id%'
        oauth_google_client_id: '%oauth_google_client_id%'
    paths:
        '%kernel.project_dir%/templates': ~

    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig'

when@test:
    twig:
        strict_variables: true
