base:
    resource: '../src/Controller/'
    type: attribute
    prefix: /

public:
    resource: '../src/Controller/Public/'
    type: attribute
    prefix: /

backoffice:
    resource: '../src/Controller/Backoffice/'
    type: attribute
    prefix: /backoffice

api:
    resource: '../src/Controller/API/'
    type: attribute
    prefix: /api